
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.209:3306/setup?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8086
  map:
    ##China CN
    Anhui: SH,HK,BJ,SG
    Beijing: BJ,SH,HK,SG
    Chongqing: HK,SH,BJ,SG
    Fujian: HK,SH,BJ,SG
    Gansu: BJ,SH,HK,SG
    Guangdong: HK,SH,BJ,SG
    Guangxi: HK,SH,BJ,SG
    Guizhou: HK,SH,BJ,SG
    Hainan: HK,SH,BJ,SG
    Hebei: BJ,SH,HK,SG
    Heilongjiang: BJ,SH,HK,SG
    Henan: BJ,SH,HK,SG
    Hubei: BJ,SH,HK,SG
    Hunan: SH,BJ,HK,SG
    Jiangsu: SH,BJ,HK,SG
    Jiangxi: HK,SH,BJ,SG
    Jilin: BJ,SH,HK,SG
    Liaoning: BJ,SH,HK,SG
    "[Nei Mongol]": BJ,SH,HK,SG
    Ningxia: BJ,SH,HK,SG
    Qinghai: BJ,SH,HK,SG
    Shaanxi: BJ,SH,HK,SG
    Shandong: BJ,SH,HK,SG
    Shanghai: SH,HK,BJ,SG
    Shanxi: BJ,SH,HK,SG
    Sichuan: HK,SH,BJ,SG
    Tianjin: BJ,SH,HK,SG
    Xinjiang: BJ,HK,SH,SG
    Xizang: HK,BJ,SH,SG
    Yunnan: HK,SH,BJ,SG
    Zhejiang: SH,HK,BJ,SG
    ##中国香港 HK Hong Kong  ---   ---
    "[Hong Kong]": HK,SH,BJ,SG
    ##中国澳门 MO Macao Macao Macau
    Macao: HK,SH,BJ,SG
    ##中国台湾
    "[Taiwan (Province of China)]": HK,SH,BJ,SG
    ##海外 内陆已经配好了
    US: SG,HK,BJ,SH
    AU: SG,HK,BJ,SH
    JP: SG,HK,BJ,SH
    TH: SG,HK,BJ,SH
    IN: SG,HK,BJ,SH
    MY: SG,HK,BJ,SH
    KR: SG,HK,BJ,SH
    "[-]": SG,HK,BJ,SH
    SG: SG,HK,BJ,SH
    HK: SG,HK,BJ,SH
    TW: SG,HK,BJ,SH
    KH: SG,HK,BJ,SH
    BR: SG,HK,BJ,SH
    PH: SG,HK,BJ,SH
    VN: SG,HK,BJ,SH
    NO: SG,HK,BJ,SH
    ES: SG,HK,BJ,SH
    FR: SG,HK,BJ,SH
    NL: SG,HK,BJ,SH
    CZ: SG,HK,BJ,SH
    GB: SG,HK,BJ,SH
    DE: SG,HK,BJ,SH
    AT: SG,HK,BJ,SH
    CH: SG,HK,BJ,SH
    IT: SG,HK,BJ,SH
    GR: SG,HK,BJ,SH
    PL: SG,HK,BJ,SH
    BE: SG,HK,BJ,SH
    IE: SG,HK,BJ,SH
    DK: SG,HK,BJ,SH
    PT: SG,HK,BJ,SH
    SE: SG,HK,BJ,SH
    GH: SG,HK,BJ,SH
    TR: SG,HK,BJ,SH
    RU: SG,HK,BJ,SH
    CM: SG,HK,BJ,SH
    ZA: SG,HK,BJ,SH
    FI: SG,HK,BJ,SH
    AE: SG,HK,BJ,SH
    HU: SG,HK,BJ,SH
    JO: SG,HK,BJ,SH
    RO: SG,HK,BJ,SH
    LU: SG,HK,BJ,SH
    AR: SG,HK,BJ,SH
    UG: SG,HK,BJ,SH
    AM: SG,HK,BJ,SH
    TZ: SG,HK,BJ,SH
    BI: SG,HK,BJ,SH
    UY: SG,HK,BJ,SH
    CL: SG,HK,BJ,SH
    BG: SG,HK,BJ,SH
    UA: SG,HK,BJ,SH
    EG: SG,HK,BJ,SH
    CA: SG,HK,BJ,SH
    IL: SG,HK,BJ,SH
    QA: SG,HK,BJ,SH
    MD: SG,HK,BJ,SH
    HR: SG,HK,BJ,SH
    SC: SG,HK,BJ,SH
    IQ: SG,HK,BJ,SH
    LV: SG,HK,BJ,SH
    EE: SG,HK,BJ,SH
    UZ: SG,HK,BJ,SH
    SK: SG,HK,BJ,SH
    KZ: SG,HK,BJ,SH
    GE: SG,HK,BJ,SH
    AL: SG,HK,BJ,SH
    PS: SG,HK,BJ,SH
    SA: SG,HK,BJ,SH
    CY: SG,HK,BJ,SH
    MT: SG,HK,BJ,SH
    LT: SG,HK,BJ,SH
    CR: SG,HK,BJ,SH
    IR: SG,HK,BJ,SH
    MX: SG,HK,BJ,SH
    ID: SG,HK,BJ,SH
    RS: SG,HK,BJ,SH
    BH: SG,HK,BJ,SH
    UM: SG,HK,BJ,SH
    CO: SG,HK,BJ,SH
    BM: SG,HK,BJ,SH
    PA: SG,HK,BJ,SH
    SY: SG,HK,BJ,SH
    LB: SG,HK,BJ,SH
    AZ: SG,HK,BJ,SH
    KE: SG,HK,BJ,SH
    DJ: SG,HK,BJ,SH
    ZW: SG,HK,BJ,SH
    ZM: SG,HK,BJ,SH
    CD: SG,HK,BJ,SH
    AO: SG,HK,BJ,SH
    OM: SG,HK,BJ,SH
    IS: SG,HK,BJ,SH
    SI: SG,HK,BJ,SH
    MK: SG,HK,BJ,SH
    LI: SG,HK,BJ,SH
    JE: SG,HK,BJ,SH
    BA: SG,HK,BJ,SH
    PY: SG,HK,BJ,SH
    BY: SG,HK,BJ,SH
    PE: SG,HK,BJ,SH
    KG: SG,HK,BJ,SH
    VE: SG,HK,BJ,SH
    IM: SG,HK,BJ,SH
    GG: SG,HK,BJ,SH
    GI: SG,HK,BJ,SH
    LY: SG,HK,BJ,SH
    YE: SG,HK,BJ,SH
    RE: SG,HK,BJ,SH
    JM: SG,HK,BJ,SH
    GP: SG,HK,BJ,SH
    MQ: SG,HK,BJ,SH
    KW: SG,HK,BJ,SH
    LK: SG,HK,BJ,SH
    SZ: SG,HK,BJ,SH
    BT: SG,HK,BJ,SH
    BN: SG,HK,BJ,SH
    PM: SG,HK,BJ,SH
    LA: SG,HK,BJ,SH
    GU: SG,HK,BJ,SH
    MP: SG,HK,BJ,SH
    DO: SG,HK,BJ,SH
    NG: SG,HK,BJ,SH
    NZ: SG,HK,BJ,SH
    EC: SG,HK,BJ,SH
    PR: SG,HK,BJ,SH
    VI: SG,HK,BJ,SH
    SR: SG,HK,BJ,SH
    BO: SG,HK,BJ,SH
    BD: SG,HK,BJ,SH
    PK: SG,HK,BJ,SH
    PG: SG,HK,BJ,SH
    TL: SG,HK,BJ,SH
    SB: SG,HK,BJ,SH
    VU: SG,HK,BJ,SH
    FJ: SG,HK,BJ,SH
    CK: SG,HK,BJ,SH
    TO: SG,HK,BJ,SH
    NP: SG,HK,BJ,SH
    MO: SG,HK,BJ,SH
    TT: SG,HK,BJ,SH
    LS: SG,HK,BJ,SH
    MA: SG,HK,BJ,SH
    VG: SG,HK,BJ,SH
    KN: SG,HK,BJ,SH
    AG: SG,HK,BJ,SH
    VC: SG,HK,BJ,SH
    KY: SG,HK,BJ,SH
    LC: SG,HK,BJ,SH
    MM: SG,HK,BJ,SH
    GD: SG,HK,BJ,SH
    CW: SG,HK,BJ,SH
    BB: SG,HK,BJ,SH
    BS: SG,HK,BJ,SH
    GT: SG,HK,BJ,SH
    DM: SG,HK,BJ,SH
    TM: SG,HK,BJ,SH
    TK: SG,HK,BJ,SH
    MV: SG,HK,BJ,SH
    AF: SG,HK,BJ,SH
    NC: SG,HK,BJ,SH
    MN: SG,HK,BJ,SH
    WF: SG,HK,BJ,SH
    MU: SG,HK,BJ,SH
    SM: SG,HK,BJ,SH
    ME: SG,HK,BJ,SH
    SV: SG,HK,BJ,SH
    BZ: SG,HK,BJ,SH
    AD: SG,HK,BJ,SH
    MC: SG,HK,BJ,SH
    GL: SG,HK,BJ,SH
    WS: SG,HK,BJ,SH
    TJ: SG,HK,BJ,SH
    FO: SG,HK,BJ,SH
    HT: SG,HK,BJ,SH
    MF: SG,HK,BJ,SH